http:
  routers:
    hass:
      entryPoints:
        - "https"
      rule: "Host(`hass.{{ domain }}`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: hass

    collabora:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.{{ domain }}`) && PathPrefix(`/cool/`)"
      service: "nextcloud"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "collabora-headers"
        - "collabora-websocket" 
      priority: 300

    nextcloud-websocket:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.{{ domain }}`) && (PathPrefix(`/push/`) || PathPrefix(`/apps/notify_push/`) || PathPrefix(`/browser/`))"
      service: "nextcloud"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "nextcloud-websocket"
      priority: 200

    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.{{ domain }}`)"
      service: "nextcloud"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "nextcloud-headers"
        - "nextcloud-redirects"
      priority: 100

  services:
    hass:
      loadBalancer:
        servers:
          - url: "http:/{{ ansible_default_ipv4.address }}:8123/"
        passHostHeader: true
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000"
        passHostHeader: true
        responseForwarding:
          flushInterval: "100ms"
        serversTransport: "nextcloud-transport"

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
    nextcloud-websocket:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        
    collabora-websocket:
      headers:
        customRequestHeaders:
          Connection: "Upgrade"
          Upgrade: "websocket"
        hostsProxyHeaders:
          - "X-Forwarded-Host"

    collabora-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "frame-ancestors 'self' https://nextcloud.{{ domain }}"

    nextcloud-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "frame-ancestors 'self'"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders: 
          X-Forwarded-Proto: "https"
  
    nextcloud-redirects:
      redirectRegex:
        permanent: true
        regex: "https://nextcloud.{{ domain }}/.well-known/(card|cal)dav"
        replacement: "https://nextcloud.{{ domain }}/remote.php/dav/"

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

  serversTransports:
    nextcloud-transport:
      forwardingTimeouts:
        dialTimeout: "30s"
        responseHeaderTimeout: "30s"
        idleConnTimeout: "1h"

CLI:
  serversTransport:
    insecureSkipVerify: true
