http:
  routers:
    hass:
      entryPoints:
        - "https"
      rule: "Host(`hass.{{ domain }}`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: hass
    nextcloud:
      entryPoints:
        - "https"
      rule: "Host(`nextcloud.{{ domain }}`)"
      service: "nextcloud"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "nextcloud-headers"
        - "nextcloud-redirects"

      
  services:
    hass:
      loadBalancer:
        servers:
          - url: "http:/{{ ansible_default_ipv4.address }}:8123/"
        passHostHeader: true
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://nextcloud-aio-apache:11000"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        
    nextcloud-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        customFrameOptionsValue: "SAMEORIGIN"
        contentSecurityPolicy: "frame-ancestors 'self'"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
  
    nextcloud-redirects:
      redirectRegex:
        permanent: true
        regex: "https://nextcloud.{{ domain }}/.well-known/(card|cal)dav"
        replacement: "https://nextcloud.{{ domain }}/remote.php/dav/"
    # nextcloud-secure-headers:
    #   headers:
    #     hostsProxyHeaders:
    #       - "X-Forwarded-Host"
    #     referrerPolicy: "same-origin"

        # Find video from Jims Garage
    # crowdsec-bouncer:
    #   forwardauth:
    #     address: http://bouncer-traefik:8000/api/v1/forwardAuth
    #     trustForwardHeader: true
  
    # nextcloud-chain:
    #   chain:
    #     middlewares:
    #       # - ... (e.g. rate limiting middleware)
    #       - https-redirectscheme
    #       - nextcloud-secure-headers

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    # default-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #     - "10.0.0.0/8"
    #     - "192.168.0.0/16"
    #     - "172.16.0.0/12"


CLI:
  serversTransport:
    insecureSkipVerify: true
# (https://doc.traefik.io/traefik/routing/overview/#insecureskipverify)