---

- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "koenkk/zigbee2mqtt"
    pull: yes
    state: 'started'
    ports:
      - "8081:8080"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/zigbee2mqtt_data:/app/data"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0:rwm"
      # - "/dev/ttyUSB2:/dev/ttyUSB2:rwm"
    groups:
      - dialout
    restart_policy: unless-stopped
