---

- name: Make sure the {{ container_name }} container is created and running
  # become: true
  docker_container:
    name: "{{ container_name }}"
    image: "esphome/esphome"
    pull: yes
    ports:
      - "6052:6052"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      ESPHOME_DASHBOARD_USE_PING: "true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{ config_root }}/esphome_config:/config"
    state: 'started'
    restart_policy: unless-stopped
