---
# OMV Server - Full services
- hosts: omv_server

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  

  roles:
    - role: setup/user_setup
      become: yes
      tags:
        - setup
        - user_setup
        - user-setup
  
    - role: setup/docker
      become: yes
      tags:
        - setup
        - docker

    # - role: setup/nfs
    #   become: yes
    #   tags:
    #     - setup
    #     - nfs 
  
    # - role: setup/samba
    #   tags:
    #     - setup
    #     - samba 
    - role: services/paperless-ngx
      become: true
      tags:
        - paperless
        - paperless-ngx
        - services

    - role: services/gitea
      tags:
        - services
        - containers
        - gitea
        
    - role: services/gitlab
      tags:
        - services
        - containers
        - gitlab

    - role: services/nextcloud
      tags:
        - services
        - nextcloud

    - role: services/nextcloud-aio
      tags:
        - services
        - nextcloud-aio

    - role: pihole
      become: yes
      tags:
        - services
        - pihole
        - dns

    - role: nebula-sync
      become: yes
      tags:
        - services
        - pihole
        - nebula-sync
        - sync

    # - role: services/seafile
    #   tags:
    #     - services
    #     - seafile

    - role: heimdall  
      tags:
        - services
        - containers
        - heimdall

    - role: media/jellyfin  
      tags:
        - media
        - containers
        - jellyfin

    - role: media/airsonic  
      tags:
        - media
        - containers
        - airsonic

    - role: arr/sonarr  
      tags:
        - arr
        - containers
        - sonarr

    - role: arr/radarr  
      tags:
        - arr
        - containers
        - radarr

    - role: arr/lidarr  
      tags:
        - arr
        - containers
        - lidarr

    - role: services/portainer  
      tags:
        - containers
        - portainer

    - role: arr/bazarr  
      tags:
        - arr
        - containers
        - bazarr

    - role: arr/prowlarr  
      tags:
        - arr
        - containers
        - prowlarr

    - role: arr/kapowarr  
      tags:
        - arr
        - containers
        - kapowarr
        - comics

    - role: arr/mylar3  
      tags:
        - arr
        - containers
        - mylar3
        - comics

    # - role: arr/tdarr  
    #   tags:
    #     - arr
    #     - containers
    #     - tdarr

    - role: services/vaultwarden  
      tags:
        - services
        - containers
        - vaultwarden

    # - role:  monitor/loki  
    #   tags:
    #     - monitor
    #     - loki
        
    # - role:  monitor/prometheus  
    #   tags:
    #     - monitor
    #     - prometheus

    # - role:  monitor/promtail  
    #   tags:
    #     - monitor
    #     - promtail

    # - role:  monitor/grafana  
    #   tags:
    #     - monitor
    #     - grafana

    - role: home-automation/homeassistant  
      tags:
        - homeassistant
        - containers
        - home-automation
  

    - role: home-automation/esphome  
      tags:
        - esphome
        - containers
        - home-automation
  
    - role: home-automation/mqtt  
      tags:
        - mqtt
        - containers
        - home-automation

    - role: home-automation/zigbee2mqtt  
      tags:
        - zigbee2mqtt
        - containers
        - home-automation
        
    - role: home-automation/musicassistant 
      tags:
        - music-assistant
        - containers
        - home-automation

    - role: home-automation/frigate  
      tags:
        - frigate       
        
    - role: home-automation/nodered  
      tags:
        - nodered
        - node-red
        - containers
        - home-automation

    - role: minecraft  
      tags:
        - minecraft

    - role: crafty  
      tags:
        - crafty

    - role: services/calibre  
      tags:
      - containers
      - calibre

    - role: services/calibre-web-automated
      tags:
      - containers
      - calibre-web-automated
      - ebooks
      - cwa

    - role: services/booklore  
      tags:
      - containers
      - booklore
      - books

    - role: services/komga  
      tags:
      - containers
      - komga
      - comics

    - role: services/audiobookshelf  
      tags:
      - containers
      - audiobookshelf

    - role: services/openbooks  
      tags:
      - containers
      - openbooks

    - role: services/trilium  
      tags:
        - containers
        - trilium

    - role: services/ubooquity  
      tags:
        - containers
        - ubooquity

    - role: services/kavita  
      tags:
        - containers
        - kavita

    - role: services/immich  
      tags:
        - containers
        - immich

    - role: services/watchtower  
      tags:
        - containers
        - watchtower

    - role: services/mealie  
      tags:
        - containers
        - mealie

    - role: services/gramps  
      tags:
        - containers
        - gramps

    - role: services/open-speed-test  
      tags:
        - containers
        - speedtest

    - role: services/syncthing 
      become: yes 
      tags:
        - containers
        - syncthing

    - role: dashy 
      tags:
        - containers
        - dashy

    - role: homepage 
      tags:
        - containers
        - homepage

    - role: services/vscode 
      tags:
        - containers
        - vscode

    - role: services/duplicati 
      tags:
        - containers
        - duplicati

    - role: services/traefik
      tags:
        - containers
        - traefik
        - trafik

    - role: services/cloudflared  
      tags:
        - cloudflare
        - cloudflared

    - role: arr/transmission-openvpn 
      tags:
        - containers
        - transmission
        - transmission-openvpn

    - role: arr/qbittorrent-vpn
      tags:
        - containers
        - qbit
        - qbittorrent
        - qbittorrent-vpn

    - role: services/collabora
      tags:
        - containers
        - collabora

    - role: services/logseq
      tags:
        - containers
        - logseq

    - role: services/trilium-next
      tags:
        - containers
        - trilium
        - notes

    - role: services/n8n
      tags:
        - containers
        - services
        - n8n
        - automation

# Pi-hole Backup Server - Minimal services only
- hosts: pihole_backup
  tags:
    - pihole

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml

  roles:
    - role: setup/user_setup
      become: yes
      tags:
        - setup
        - user_setup
        - user-setup
  
    - role: setup/docker
      become: yes
      tags:
        - setup
        - docker

    - role: pihole
      become: yes
      tags:
        - services
        - pihole
        - dns
        
# TODO: wire containers through gluetun 

# indexer 

        # TODO: wrap up the media suite and verify that it can be served
        # Store it on nfs mount to  nas
        
        # https://www.fuzzygrim.com/posts/selfhosted-setup
