---
- hosts: all

  vars_files:
    - ./vars/vault.yml
    - ./vars/vars.yml
  

  roles:
    - role: setup/user_setup
      become: yes
      tags:
        - setup
        - user_setup
        - user-setup
  
    - role: setup/docker
      become: yes
      tags:
        - setup
        - docker

    # - role: setup/nfs
    #   tags:
    #     - setup
    #     - nfs 
  
    # - role: setup/samba
    #   tags:
    #     - setup
    #     - samba 

    - role: services/nextcloud
      tags:
        - services
        # - containers
        - nextcloud

    # - role: services/seafile
    #   tags:
    #     - services
    #     - seafile

    - role: heimdall  
      tags:
        - services
        - containers
        - heimdall

    - role: media/jellyfin  
      tags:
        - media
        - containers
        - jellyfin
  
    # - role: media/plex  
    #   tags:
    #     - media
    #     - containers
    #     - plex

    - role: arr/sonarr  
      tags:
        - arr
        - containers
        - sonarr

    - role: arr/radarr  
      tags:
        - arr
        - containers
        - radarr

    - role: arr/lidarr  
      tags:
        - arr
        - containers
        - lidarr

    - role: arr/readarr  
      tags:
        - arr
        - containers
        - readarr

    - role: services/portainer  
      tags:
        - arr
        - containers
        - portainer

    - role: arr/bazarr  
      tags:
        - arr
        - containers
        - bazarr

    - role: arr/prowlarr  
      tags:
        - arr
        - containers
        - prowlarr

    # - role: arr/transmission  
    #   tags:
    #     - arr
    #     - containers
    #     - transmission

    - role: services/vaultwarden  
      tags:
        - services
        - containers
        - vaultwarden

    # - role:  monitor/loki  
    #   tags:
    #     - monitor
    #     - loki
        
    # - role:  monitor/prometheus  
    #   tags:
    #     - monitor
    #     - prometheus

    # - role:  monitor/promtail  
    #   tags:
    #     - monitor
    #     - promtail

    # - role:  monitor/grafana  
    #   tags:
    #     - monitor
    #     - grafana

    - role:  home-automation/homeassistant  
      tags:
        - homeassistant
        - containers
        - home-automation
  

    - role:  home-automation/esphome  
      tags:
        - esphome
        - containers
        - home-automation
  
    - role:  home-automation/mqtt  
      tags:
        - mqtt
        - containers
        - home-automation

    - role:  home-automation/zigbee2mqtt  
      tags:
        - zigbee2mqtt
        - containers
        - home-automation
        
    # - role:  home-automation/frigate  
    #   tags:
    #     - frigate
    #     - containers
    #     - home-automation
        
    - role:  home-automation/nodered  
      tags:
        - nodered
        - node-red
        - containers
        - home-automation

    - role:  minecraft  
      tags:
        - minecraft

    - role: services/calibre  
      tags:
      - containers
        - calibre

    - role: services/trilium  
      tags:
        - containers
        - trilium

    - role: services/ubooquity  
      tags:
        - containers
        - ubooquity

    - role: services/kavita  
      tags:
        - containers
        - kavita

    - role: services/photoprism  
      tags:
        - containers
        - photoprism

    - role: services/watchtower  
      tags:
        - containers
        - watchtower

    # - role: services/traefik  
    #   tags:
    #     - containers
    #     - traefik
    #     - trafik

    - role: arr/transmission-openvpn 
      tags:
        - containers
        - transmission-openvpn

# TODO: wire containers through gluetun 

# indexer 

        # TODO: wrap up the media suite and verify that it can be served
        # Store it on nfs mount to  nas
        
        # https://www.fuzzygrim.com/posts/selfhosted-setup
