---
- name: Make sure the kavita container is created and running
  docker_container:
    image: jvmilazz0/kavita:latest
    name: kavita
    networks:
      - name: media_network
    dns_servers:
      - "{{ server_ip }}"  # Pi-hole server
    ports:
      - 5002:5000
    pull: yes
    state: 'started'
    recreate: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/kavita_config:/kavita/config"
      - "{{ data_root }}/media/kavita:/media"
    restart_policy: unless-stopped
