---
- name: "Make sure - NextCloud All In One container is created and running"
  docker_container:
    container_default_behavior: compatibility
    networks_cli_compatible: yes
    name: nextcloud-aio-mastercontainer 
    image: nextcloud/all-in-one:latest
    restart_policy: unless-stopped
    published_ports:
      - "8102:8080"
      # - "11000:11000"
    networks:
      - name: proxy
        aliases:
          - nextcloud
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      NEXTCLOUD_DATADIR: "{{ brick_root }}/nextcloud/ncdata"
      NEXTCLOUD_MOUNT: "{{ brick_root }}/nextcloud"
      APACHE_PORT: "11000"
      APACHE_IP_BINDING: "0.0.0.0"
      APACHE_ADDITIONAL_NETWORK: "proxy"
      SKIP_DOMAIN_VALIDATION: "true"
      NC_DOMAIN: "nextcloud.{{ domain }}"
      AIO_DISABLE_DOMAINCHECK: "true"
      NEXTCLOUD_ADDITIONAL_TRUSTED_DOMAINS: "nextcloud-aio-apache"  # Add this
      NEXTCLOUD_ADDITIONAL_APCU_FAST_SHUTDOWN: "1"  # Optional performance improvement
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
    memory: "{{ nextcloud_memory_limit }}"
    memory_reservation: "{{ nextcloud_memory_reservation }}"
    cpu_shares: 1024
    security_opts:
      - no-new-privileges:true
