---
- name: Make sure the radarr container is created and running
  docker_container:
    image: "ghcr.io/linuxserver/radarr"
    name: radarr
    networks:
      - name: media_network
    ports:
      - 7878:7878
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/radarr_config:/config"
      # - "{{ data_root }}/media/movies:/movies"
      # - "{{ data_root }}/media/anime:/anime"
      # - "{{ data_root }}/media/tvshows:/tvshows"
      - "{{ data_root }}/media:/media"
      # - "{{ data_root }}/qbittorrent/downloads:/downloads"
      - "{{ data_root }}/transmission/data/completed:/data/completed"
    restart_policy: unless-stopped

