---
- name: Make sure the mealie container is created and running
  docker_container:
    image: hkotel/mealie:latest
    name: mealie
    # With no ports, it can only be accessed through traefik
    # ports:
    #   - "9092:80"
    networks:
      - name: proxy
    dns_servers:
      - "{{ server_ip }}"  # Pi-hole server
    labels:
      traefik.enable: "true"
      traefik.http.routers.mealie.entrypoints: "http"
      # This syntax allows cloudflare tunnel to host mealie.{{ domain }} which points to local mealie-in.{{ domain }} over https
      # Both mealie.{{ domain }} and mealie-in.{{ domain }} must be configured in local dns (pi-hole)
      # https://www.youtube.com/watch?v=yMmxw-DZ5Ec
      traefik.http.routers.mealie.rule: "Host(`mealie.{{ domain }}`)||Host(`mealie-in.{{ domain }}`)"
      traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.mealie.middlewares: "mealie-https-redirect"
      traefik.http.routers.mealie-secure.entrypoints: "https"
      traefik.http.routers.mealie-secure.rule: "Host(`mealie.{{ domain }}`)||Host(`mealie-in.{{ domain }}`)"
      traefik.http.routers.mealie-secure.tls: "true"
      traefik.http.routers.mealie-secure.service: "mealie"
    pull: yes
    state: 'started'
    recreate: yes
    env:
      # DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # ALLOW_SIGNUP: "false"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ data_root }}/mealie_data:/app/data/"
    restart_policy: unless-stopped

# Username: changeme@email.com
# Password: MyPassword