---
- name: Create a gramps network
  docker_network:
    name: gramps

- name: Make sure the gramps redis container is created and running
  docker_container:
    image: "redis:{{ gramps_redis_version }}"
    name: grampsweb_redis
    state: 'started'
    restart_policy: unless-stopped
    networks:
      - name: gramps

- name: Make sure the gramps celery container is created and running
  docker_container:
    image: "ghcr.io/gramps-project/grampsweb:{{ gramps_version }}"
    name: grampsweb_celery
    networks:
      - name: gramps
    pull: yes
    state: 'started'
    command: 'celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2'
    env:
      GRAMPSWEB_TREE: "{{ gramps_tree_name }}"
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb_redis:6379/1"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes: &gramps_volumes
      - "{{ data_root }}/gramps_data/users:/app/users"
      - "{{ data_root }}/gramps_data/index:/app/indexdir"
      - "{{ data_root }}/gramps_data/thumb_cache:/app/thumbnail_cache"
      - "{{ data_root }}/gramps_data/cache:/app/cache"
      - "{{ data_root }}/gramps_data/secret:/app/secret"
      - "{{ data_root }}/gramps_data/db:/root/.gramps/grampsdb"
      - "{{ data_root }}/gramps_data/media:/app/media"
    tmpfs:
      - /tmp:rw,exec
    restart_policy: unless-stopped

- name: Make sure the gramps container is created and running
  docker_container:
    image: "ghcr.io/gramps-project/grampsweb:{{ gramps_version }}"
    name: grampsweb
    ports:
      - "5001:5000"
    networks:
      - name: gramps
      - name: proxy
    dns_servers:
      - "{{ server_ip }}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gramps.entrypoints: "http"
      traefik.http.routers.gramps.rule: "Host(`gramps.{{ domain }}`)"
      traefik.http.middlewares.gramps-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.gramps.middlewares: "gramps-https-redirect"
      traefik.http.routers.gramps-secure.entrypoints: "https"
      traefik.http.routers.gramps-secure.rule: "Host(`gramps.{{ domain }}`)"
      traefik.http.routers.gramps-secure.tls: "true"
      traefik.http.routers.gramps-secure.service: "gramps"
      traefik.http.services.gramps.loadbalancer.server.port: "5000"
    pull: yes
    state: 'started'
    env:
      GRAMPSWEB_TREE: "{{ gramps_tree_name }}"
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: "redis://grampsweb_redis:6379/1"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes: *gramps_volumes
    tmpfs:
      - /tmp:rw,exec
    restart_policy: unless-stopped
