# - name: Create Cal.com directories
#   file:
#     path: "{{ item }}"
#     state: directory
#     mode: '0755'
#   loop:
#     - "{{ calcom_data_path }}"
#     - "{{ calcom_data_path }}/uploads"
#     - "{{ postgres_data_path }}"

- name: Deploy PostgreSQL container
  docker_container:
    name: postgres-calcom
    image: postgres:14
    state: started
    restart_policy: always
    networks:
      - name: proxy
    volumes:
      - "{{ postgres_data_path }}:/var/lib/postgresql/data"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      POSTGRES_DB: "{{ postgres_db }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_PASSWORD: "{{ postgres_password }}"

- name: Create environment file
  template:
    src: env.j2
    dest: "{{ calcom_data_path }}/.env"
    mode: '0600'

- name: Deploy Cal.com container
  docker_container:
    name: calcom-app
    image: calcom/cal.com:latest
    state: started
    restart_policy: always
    networks:
      - name: proxy
    volumes:
      - "{{ calcom_data_path }}/uploads:/app/uploads"
    env_file: "{{ calcom_data_path }}/.env"
    working_dir: /calcom
    hostname: "cal.{{ domain }}"
    command: >
      sh -c "
        yarn workspace @calcom/prisma prisma generate &&
        yarn workspace @calcom/prisma prisma migrate deploy &&
        yarn start
      "
    labels:
      traefik.enable: "true"
      traefik.http.routers.calcom.rule: "Host(`cal.{{ domain }}`)"
      traefik.http.routers.calcom.entrypoints: "https"
      traefik.http.routers.calcom.tls: "true"
      traefik.http.services.calcom.loadbalancer.server.port: "3000"
      traefik.http.routers.calcom-http.rule: "Host(`cal.{{ domain }}`)"
      traefik.http.routers.calcom-http.entrypoints: "http"
      traefik.http.routers.calcom-http.middlewares: "calcom-https-redirect"
      traefik.http.middlewares.calcom-https-redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.calcom-https-redirect.redirectscheme.permanent: "true"


