http:
  routers:
    hass:
      entryPoints:
        - "https"
      rule: "Host(`hass.coulter.rocks`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: hass
      
  services:
    hass:
      loadBalancer:
        servers:
          - url: "http://192.168.1.36:8123/"
        passHostHeader: true

  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        
        # Find video from Jims Garage
    # crowdsec-bouncer:
    #   forwardauth:
    #     address: http://bouncer-traefik:8000/api/v1/forwardAuth
    #     trustForwardHeader: true
  
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    # default-whitelist:
    #   ipWhiteList:
    #     sourceRange:
    #     - "10.0.0.0/8"
    #     - "192.168.0.0/16"
    #     - "172.16.0.0/12"

    secured:
      chain:
        middlewares:
        # - default-whitelist
        - default-headers

CLI:
  serversTransport:
    insecureSkipVerify: true
# (https://doc.traefik.io/traefik/routing/overview/#insecureskipverify)