---
# cd /mnt/config/surfshark

# https://hub.docker.com/r/binhex/arch-qbittorrentvpn

#  TODO: set script to download current surfshark opvns to the dir at surfshark_custom
# openvpn us-dtw.prod.surfshark.com_udp.ovpn 

# I need to mount /config/qBittransmission/data to a diffferent volume and 
# docker does not support volumes that are subdirectories of named volumes
- name: Create symbolic for data 
  become: true
  file:
    src: "{{ data_root }}/qbittorrent/data"
    dest: "{{ config_root }}/qbittorrent_config/qBittorrent/data"
    state: link

# I need to mount /config/qBittransmission/data to a diffferent volume and 
# docker does not support volumes that are subdirectories of named volumes
- name: Create symbolic for downloads 
  become: true
  file:
    src: "{{ data_root }}/qbittorrent/downloads"
    dest: "{{ config_root }}/qbittorrent_config/qBittorrent/downloads"
    state: link

- name: Make sure the qbittorrent vpn container is created and running
  become: true
  docker_container:
    image: "binhex/arch-qbittorrentvpn"
    name: qbittorrentvpn
    capabilities:
      - NET_ADMIN
    ports:
      - '8085:8085'
      # - '8085:8080'
      - '8118:8118'
      - '9118:9118'
      - '58946:58946'
      - '58946:58946/udp'
    pull: yes
    networks:
      - name: media_network
    state: started
    recreate: yes
    env:
      VPN_ENABLED: "yes"
      # VPN_TYPE: "wireguard"
      VPN_USER: "{{ vpn_username }}"
      VPN_PASS: "{{ vpn_password }}"
      LAN_NETWORK: "192.168.0.0/16"
      VPN_CLIENT: "openvpn"
      VPN_PROV: "custom"
      WEBUI_PORT: "8085"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/qbittorrent_config:/config"
      # sym links are resolved in kernal space so I have to mount 
      # the data and downloads folders too.
      - "{{ data_root }}/qbittorrent/data:{{ data_root }}/qbittorrent/data"
      - "{{ data_root }}/qbittorrent/downloads:{{ data_root }}/qbittorrent/downloads"
    restart_policy: unless-stopped

       
# sg-sng-st010.prod.surfshark.com_udp.ovpn
# sg-sng.prod.surfshark.com_tcp.ovpn
# sg-sng.prod.surfshark.com_udp.ovpn
# si-lju.prod.surfshark.com_tcp.ovpn
# si-lju.prod.surfshark.com_udp.ovpn
# sk-bts.prod.surfshark.com_tcp.ovpn
# sk-bts.prod.surfshark.com_udp.ovpn
# th-bkk.prod.surfshark.com_tcp.ovpn
# th-bkk.prod.surfshark.com_udp.ovpn
# tr-ist.prod.surfshark.com_tcp.ovpn
# tr-ist.prod.surfshark.com_udp.ovpn
# tw-tai.prod.surfshark.com_tcp.ovpn
# tw-tai.prod.surfshark.com_udp.ovpn
# ua-iev.prod.surfshark.com_tcp.ovpn
# ua-iev.prod.surfshark.com_udp.ovpn
# uk-edi.prod.surfshark.com_tcp.ovpn
# uk-edi.prod.surfshark.com_udp.ovpn
# uk-gla.prod.surfshark.com_tcp.ovpn
# uk-gla.prod.surfshark.com_udp.ovpn
# uk-lon-mp001.prod.surfshark.com_tcp.ovpn
# uk-lon-mp001.prod.surfshark.com_udp.ovpn
# uk-lon-st001.prod.surfshark.com_tcp.ovpn
# uk-lon-st001.prod.surfshark.com_udp.ovpn
# uk-lon-st002.prod.surfshark.com_tcp.ovpn
# uk-lon-st002.prod.surfshark.com_udp.ovpn
# uk-lon-st003.prod.surfshark.com_tcp.ovpn
# uk-lon-st003.prod.surfshark.com_udp.ovpn
# uk-lon-st004.prod.surfshark.com_tcp.ovpn
# uk-lon-st004.prod.surfshark.com_udp.ovpn
# uk-lon-st005.prod.surfshark.com_tcp.ovpn
# uk-lon-st005.prod.surfshark.com_udp.ovpn
# uk-man.prod.surfshark.com_tcp.ovpn
# uk-man.prod.surfshark.com_udp.ovpn
# us-ash.prod.surfshark.com_tcp.ovpn
# us-ash.prod.surfshark.com_udp.ovpn
# us-atl.prod.surfshark.com_tcp.ovpn
# us-atl.prod.surfshark.com_udp.ovpn
# us-bdn.prod.surfshark.com_tcp.ovpn
# us-bdn.prod.surfshark.com_udp.ovpn
# us-bos.prod.surfshark.com_tcp.ovpn
# us-bos.prod.surfshark.com_udp.ovpn
# us-chi.prod.surfshark.com_tcp.ovpn
# us-chi.prod.surfshark.com_udp.ovpn
# us-dal.prod.surfshark.com_tcp.ovpn
# us-dal.prod.surfshark.com_udp.ovpn
# us-den.prod.surfshark.com_tcp.ovpn
# us-den.prod.surfshark.com_udp.ovpn
# us-dtw.prod.surfshark.com_tcp.ovpn
# us-dtw.prod.surfshark.com_udp.ovpn
# us-hou.prod.surfshark.com_tcp.ovpn
# us-hou.prod.surfshark.com_udp.ovpn
# us-kan.prod.surfshark.com_tcp.ovpn
# us-kan.prod.surfshark.com_udp.ovpn
# us-las.prod.surfshark.com_tcp.ovpn
# us-las.prod.surfshark.com_udp.ovpn
# us-lax.prod.surfshark.com_tcp.ovpn
# us-lax.prod.surfshark.com_udp.ovpn
# us-ltm.prod.surfshark.com_tcp.ovpn
# us-ltm.prod.surfshark.com_udp.ovpn
# us-mia.prod.surfshark.com_tcp.ovpn
# us-mia.prod.surfshark.com_udp.ovpn
# us-nyc-mp001.prod.surfshark.com_tcp.ovpn
# us-nyc-mp001.prod.surfshark.com_udp.ovpn
# us-nyc-st001.prod.surfshark.com_tcp.ovpn
# us-nyc-st001.prod.surfshark.com_udp.ovpn
# us-nyc-st002.prod.surfshark.com_tcp.ovpn
# us-nyc-st002.prod.surfshark.com_udp.ovpn
# us-nyc-st003.prod.surfshark.com_tcp.ovpn
# us-nyc-st003.prod.surfshark.com_udp.ovpn
# us-nyc-st004.prod.surfshark.com_tcp.ovpn
# us-nyc-st004.prod.surfshark.com_udp.ovpn
# us-nyc-st005.prod.surfshark.com_tcp.ovpn
# us-nyc-st005.prod.surfshark.com_udp.ovpn
# us-nyc.prod.surfshark.com_tcp.ovpn
# us-nyc.prod.surfshark.com_udp.ovpn
# us-phx.prod.surfshark.com_tcp.ovpn
# us-phx.prod.surfshark.com_udp.ovpn
# us-sea.prod.surfshark.com_tcp.ovpn
# us-sea.prod.surfshark.com_udp.ovpn
# us-sfo-mp001.prod.surfshark.com_tcp.ovpn
# us-sfo-mp001.prod.surfshark.com_udp.ovpn
# us-sfo.prod.surfshark.com_tcp.ovpn
# us-sfo.prod.surfshark.com_udp.ovpn
# us-sjc.prod.surfshark.com_tcp.ovpn
# us-sjc.prod.surfshark.com_udp.ovpn
# us-slc.prod.surfshark.com_tcp.ovpn
# us-slc.prod.surfshark.com_udp.ovpn
# us-tpa.prod.surfshark.com_tcp.ovpn
# us-tpa.prod.surfshark.com_udp.ovpn
# uy-mvd.prod.surfshark.com_tcp.ovpn
# uy-mvd.prod.surfshark.com_udp.ovpn
# uz-tas.prod.surfshark.com_tcp.ovpn
# uz-tas.prod.surfshark.com_udp.ovpn
# ve-car.prod.surfshark.com_tcp.ovpn
# ve-car.prod.surfshark.com_udp.ovpn
# vn-hcm.prod.surfshark.com_tcp.ovpn
# vn-hcm.prod.surfshark.com_udp.ovpn
# za-jnb.prod.surfshark.com_tcp.ovpn
# za-jnb.prod.surfshark.com_udp.ovpn