---

#https://www.homeautomationguy.io/docker-tips/configuring-the-mosquitto-mqtt-docker-container-for-use-with-home-assistant/
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "eclipse-mosquitto"
    # network_mode: host
    pull: yes
    state: 'started'
    recreate: yes
    ports:
      - "1883:1883"
      - "9001:9001 "
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      NEO_LINK_MODE: "mqtt-rtsp"
    volumes:
      - "{{ config_root }}/mosquitto:/mosquitto"
    restart_policy: unless-stopped
