---
- name: Make sure the colabra container is created and running
  docker_container:
    image: collabora/code:latest
    name: colabra
    published_ports:
      - "9980:9980"
    networks:
      - name: proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.colabra.entrypoints: "http"
      # https://www.youtube.com/watch?v=yMmxw-DZ5Ec
      traefik.http.routers.colabra.rule: "Host(`colabra.{{ domain }}`)"
      traefik.http.services.colabra.loadbalancer.server.url: "http://vault.local:9980"
      traefik.http.middlewares.colabra-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.colabra.middlewares: "colabra-https-redirect"
      traefik.http.routers.colabra-secure.entrypoints: "https"
      traefik.http.routers.colabra-secure.rule: "Host(`colabra.{{ domain }}`)"
      traefik.http.routers.colabra-secure.tls: "true"
      traefik.http.routers.colabra-secure.service: "colabra"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      # To get a jwt_secret, 
      # comment out the JWT_SECRET environment variable and deploy the server
      # Then ssh onto the server and run:
      # `docker exec d25f69df7ee9 /var/www/colabra/documentserver/npm/json -f /etc/colabra/documentserver/local.json 'services.CoAuthoring.secret.session.string'`
      # then save the secret in ansible vault
      extra_params: "--o:ssl.enable=false"
      # If you want to use certbot for https instead of traefik uncomment these and add an https port.
      # LETS_ENCRYPT_DOMAIN: "{{ domain }}"
      # LETS_ENCRYPT_MAIL: "{{ primary_email }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - "{{ config_root }}/colabra_config/coolwsd:/etc/coolwsd"
    restart_policy: unless-stopped


# https://helpcenter.colabra.com/installation/docs-community-install-docker.aspx

    # sudo docker run -i -t -d -p 80:80 --restart=always \
    # -v /app/colabra/DocumentServer/logs:/var/log/colabra  \
    # -v /app/colabra/DocumentServer/data:/var/www/colabra/Data  \
    # -v /app/colabra/DocumentServer/lib:/var/lib/colabra \
    # -v /app/colabra/DocumentServer/db:/var/lib/postgresql -e JWT_SECRET=my_jwt_secret colabra/documentserver


# sudo docker run -i -t -d -p 443:443 --restart=always \
# -v /app/colabra/DocumentServer/data:/var/www/colabra/Data -e JWT_SECRET=my_jwt_secret colabra/documentserver
