---
# 
# Openvpn can be set up to only connect to specific ip by 
# adding this to the end of the .ovpn file

# route-nopull
# route 192.168.X.X 255.255.255.255

# askpass pass.txt

# Configure OPenVPN to run as a service and always connect so that it knows about 192.168.X.X backup server

# https://www.maketecheasier.com/connect-vpn-automatically-linux/

- name: Ensure backup directories exist with proper permissions
  file:
    path: "{{ backups }}/duplicati"
    state: directory
    mode: '0755'
    recurse: yes
  become: yes

- name: Make sure the duplicati container is created and running
  docker_container:
    image: duplicati/duplicati:latest
    name: duplicati
    networks:
      - name: proxy
    ports:
      - 8200:8200
    pull: yes
    state: 'started'
    # I probably don't want this because it could bork a running backup
    # recreate: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.duplicati.entrypoints: "http"
      # This syntax allows cloudflare tunnel to host duplicati.{{ domain }} which points to local duplicati-in.{{ domain }} over https
      # Both duplicati.{{ domain }} and duplicati-in.{{ domain }} must be configured in local dns (pi-hole)
      # https://www.youtube.com/watch?v=yMmxw-DZ5Ec
      traefik.http.routers.duplicati.rule: "Host(`duplicati.{{ domain }}`)"
      traefik.http.middlewares.duplicati-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.duplicati.middlewares: "duplicati-https-redirect"
      traefik.http.routers.duplicati-secure.entrypoints: "https"
      traefik.http.routers.duplicati-secure.rule: "Host(`duplicati.{{ domain }}`)"
      traefik.http.routers.duplicati-secure.tls: "true"
      traefik.http.routers.duplicati-secure.service: "duplicati"
      traefik.http.services.duplicati.loadbalancer.server.port: "8200"
    env:
      TZ: "{{ timezone }}"
      DUPLICATI_WEBSERVICE_ALLOWED_HOSTNAMES: "*,duplicati.coulter.rocks"
      DUPLICATI_HOME: "/config"
      # The official image runs as root by default, no need for PUID/PGID
    volumes:
      - "{{ config_root }}/duplicati:/config"
      - "{{ data_root }}:/data"
      - "{{ shares }}:/shares"
      - "{{ backups }}:/backups"
      - "{{ shares }}/immich:/immich"
    restart_policy: unless-stopped

