---
- name: Ensure Collabora container is running
  docker_container:
    name: "{{ collabora_container_name }}"
    image: "{{ collabora_image }}"
    state: started
    restart_policy: unless-stopped
    ports:
      - "{{ collabora_port }}:9980"
    env:
      # wtd_docker_collabora_capabilities: "MKNOD"
      # domain: ''
      domain: "nextcloud\\.coulter\\.rocks"
      # username: "{{ collabora_username }}"
      # password: "{{ collabora_password }}"
      extra_params: "{{ collabora_extra_params }}"
    networks:
      - name: "proxy"
    # volumes:
    #     - /var/run/docker.sock:/var/run/docker.sock:ro
    #     - "{{ config_root }}/collabora_config/cool:/opt/cool"
    capabilities:
      - MKNOD
  register: collabora_container

# # TODO: Start from here - requires template substitution
# - name: Copy /etc/hosts file to Collabora container
#   community.docker.docker_container_copy_into:
#     container: "{{ collabora_container_name }}"
#     path: "/etc/hosts"
#     content: "{{ lookup('file', 'collabora_hosts') }}"
#   when: collabora_container.changed

- name: Ensure Traefik dynamic config directory exists
  file:
    path: "{{ traefik_dynamic_config_dir }}"
    state: directory
    mode: "0755"

- name: Deploy Traefik dynamic config for Collabora
  template:
    src: traefik_collabora.yml.j2
    dest: "{{ traefik_dynamic_config_dir }}/traefik_collabora.yml"
    mode: "0644"
  notify: Restart Traefik
