---
# TODO: figure out version and IMMICH_VERSION
# TODO: figure out volumes and env vs volume paths

- name: Create a immich network
  docker_network:
    name: immich_network
  
- name: Setup volumes for Immich
  docker_volume:
    name: model-cache

- name: Make sure immich redis container is created and running
  docker_container:
    name: immich_redis
    image: docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    state: 'started'
    pull: yes
    networks:
      - name: immich_network
    healthcheck:
      test: ["redis-cli ping || exit 1"]
    
- name: Make sure immich postgres container is created and running
  become: yes
  docker_container:
    name: immich_postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      - name: immich_network
    state: 'started'
    pull: yes
    env:
      POSTGRES_INITDB_ARGS: '--data-checksums'
      TZ: "{{ timezone }}"
      # You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
      # The location where your uploaded files are stored
      UPLOAD_LOCATION: /usr/src/app/upload
      # The location where your database files are stored
      # DB_DATA_LOCATION: /var/lib/postgresql/data
      DB_DATA_LOCATION: /var/lib/postgresql/data
      # The Immich version to use. You can pin this to a specific version like "v1.71.0"
      IMMICH_VERSION: "{{ immich_version }}"
      # Connection secret for postgres. You should change it to a random password
      # Please use only the characters `A-Za-z0-9`, without special characters or spaces
      POSTGRES_PASSWORD: postgres
      # The values below this line do not need to be changed
      ###################################################################################
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      REDIS_HOST: nextcloud-redis

    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DATA_LOCATION in the .env file
        # - ./postgres:/var/lib/postgresql/data
        - "{{ config_root }}/immich_config/db:/var/lib/postgresql/data"
    healthcheck:
      test: >-
        pg_isready --dbname=immich --username=postgres || exit 1;
        Chksum="$$(psql --dbname=immich --username=postgres --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        echo "checksum failure count is $$Chksum";
        [ "$$Chksum" = '0' ] || exit 1
    # LOGS: /var/lib/postgresql/data/log
      # test: >-
        # pg_isready --dbname=immich --username=postgres || exit 1;
        # Chksum="$$(psql --dbname=immich --username=postgres --tuples-only --no-align
        # --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
        # echo "checksum failure count is $$Chksum";
        # [ "$$Chksum" = '0' ] || exit 1
    #  This is without checksums
      # test: >-
      #   pg_isready --dbname=immich || exit 1; Chksum="$$(psql --dbname=immich --username=postgres --tuples-only --no-align --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      #This is with data-checksums
      # test: >-
      # pg_isready --dbname=immich --username=postgres || exit 1; Chksum="$$(psql --dbname=immich --username=postgres --tuples-only --no-align --command='SELECT SUM(checksum_failures) FROM pg_stat_database')"; echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
      interval: 5m
      start_interval: 30s
      start_period: 5m
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    restart_policy: unless-stopped

- name: Make sure immich machine learning container is created and running
  become: yes
  docker_container:
    name: immich_machine_learning
    # image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    image: "ghcr.io/immich-app/immich-machine-learning:{{ immich_version }}"
    state: 'started'
    pull: yes
    networks:
      - name: immich_network
    volumes:
      - model-cache:/cache
      # - "{{ config_root }}/immich_config/model-cache:/cache"
    env:
      TZ: "{{ timezone }}"
      # You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
      # The location where your uploaded files are stored
      UPLOAD_LOCATION: /usr/src/app/upload
      # The location where your database files are stored
      # DB_DATA_LOCATION: /var/lib/postgresql/data
      DB_DATA_LOCATION: /var/lib/postgresql/data
      # The Immich version to use. You can pin this to a specific version like "v1.71.0"
      IMMICH_VERSION: "{{ immich_version }}"
      # Connection secret for postgres. You should change it to a random password
      # Please use only the characters `A-Za-z0-9`, without special characters or spaces
      DB_PASSWORD: postgres
      # The values below this line do not need to be changed
      ###################################################################################
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    restart_policy: unless-stopped
    healthcheck:
      test_cli_compatible: true

- name: Make sure the immich container is created and running
  become: yes
  docker_container:
    # image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    image: "ghcr.io/immich-app/immich-server:{{ immich_version }}"
    name: immich_server
    state: 'started'
    pull: yes
    networks:
      - name: immich_network
    ports:
      - "2283:2283"
    env:
      TZ: "{{ timezone }}"
      # You can find documentation for all the supported env variables at https://immich.app/docs/install/environment-variables
      # The location where your uploaded files are stored
      UPLOAD_LOCATION: /usr/src/app/upload
      # The location where your database files are stored
      # DB_DATA_LOCATION: /var/lib/postgresql/data
      DB_DATA_LOCATION: /var/lib/postgresql/data
      # The Immich version to use. You can pin this to a specific version like "v1.71.0"
      IMMICH_VERSION: "{{ immich_version }}"
      # Connection secret for postgres. You should change it to a random password
      # Please use only the characters `A-Za-z0-9`, without special characters or spaces
      DB_PASSWORD: postgres
      # The values below this line do not need to be changed
      ###################################################################################
      DB_USERNAME: postgres
      DB_DATABASE_NAME: immich
    # volumes:
    #   # Do not edit the next line. If you want to change the media storage location on your system, edit the value of UPLOAD_LOCATION in the .env file
    #   - "./library:/usr/src/app/upload"
    #   - /etc/localtime:/etc/localtime:ro
    volumes:
      - "{{ shares }}/immich:/usr/src/app/upload"
      - "{{ config_root }}/immich_config/db:/var/lib/postgresql/data"
      - /etc/localtime:/etc/localtime:ro
    restart_policy: unless-stopped
    healthcheck:
      test_cli_compatible: true

