---
- name: Make sure the loki container is created and running
  docker_container:
    image: "grafana/loki:2.4.0"
    name: "loki"
    networks:
      - name: media_network
    ports:
      - "3100:3100"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ data_root }}/loki:/etc/loki"
    command: -config.file=/etc/loki/loki-config.yml
    restart_policy: unless-stopped
