---

- name: Make sure the crafty control is created and running
  docker_container:
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    name: "crafty"
    ports:
      - "8001:8000" # HTTP
      - "8444:8443" # HTTPS
      - "8124:8123" # DYNMAP
      - "19132:19132/udp" # BEDROCK
      - "25500-25600:25500-25600" # MC SERV PORT RANGE
    networks:
      - name: proxy
    labels:
      traefik.enable: "true"
      traefik.http.routers.crafty.entrypoints: "https"
      traefik.http.routers.crafty.rule: "Host(`crafty.{{ domain }}`)"
      traefik.http.services.crafty.loadbalancer.server.port: "8443" # port that Crafty operates on is 8443
      traefik.http.routers.crafty.tls: "true" # tells traefik you want to use SSL/TLS to connect to your Crafty instance
      traefik.http.routers.crafty.tls.certresolver: cloudflare # OPTIONAL: If you want traefik to handle TLS certificates instead of Crafty, you should uncomment the beginning of this line and put the name of your traefik certificate resolver here
      traefik.http.services.crafty.loadbalancer.server.scheme: "https" # tell traefik to connect to Crafty via https instead of http
      traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto: "https" # enable websockets for Crafty
      traefik.http.middlewares.crafty-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.crafty.middlewares: "crafty-https-redirect,sslheader"
      traefik.http.middlewares.crafty-security.headers.stsSeconds: "315360000"
      traefik.http.middlewares.crafty-security.headers.browserXssFilter: "true"
      traefik.http.middlewares.crafty-security.headers.contentTypeNosniff: "true"
    pull: yes
    state: 'started'
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ config_root }}/crafty_data/backups:/crafty/backups"
      - "{{ config_root }}/crafty_data/servers:/crafty/servers"
      - "{{ config_root }}/crafty_data/import:/crafty/import"
      - "{{ config_root }}/crafty_config/app/config:/crafty/app/config"
      - "{{ config_root }}/crafty_config/logs:/crafty/logs"
    restart_policy: unless-stopped