---
galaxy_info:
  author: jcoulter
  description: Deploy Pi-hole DNS server using Docker with full automation
  company: Personal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - dns
    - pihole
    - docker
    - adblock

dependencies: []

collections:
  - community.docker
